# Generated by Django 4.1.7 on 2023-03-04 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_date_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 7, 29, 57, 343492, tzinfo=datetime.timezone.utc)),
        ),
    ]
