# Generated by Django 4.1.7 on 2023-03-04 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 9, 1, 28, 747222, tzinfo=datetime.timezone.utc)),
        ),
    ]
