# Generated by Django 4.1.7 on 2023-03-04 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 10, 21, 31, 180862, tzinfo=datetime.timezone.utc)),
        ),
    ]
