# Generated by Django 4.1.7 on 2023-03-05 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 9, 4, 55, 820690, tzinfo=datetime.timezone.utc)),
        ),
    ]
