# Generated by Django 4.1.7 on 2023-03-06 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 9, 46, 5, 877785, tzinfo=datetime.timezone.utc)),
        ),
    ]
