# Generated by Django 4.1.7 on 2023-03-08 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 11, 11, 52, 219925, tzinfo=datetime.timezone.utc)),
        ),
    ]
