# Generated by Django 4.1.7 on 2023-03-08 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 15, 41, 4, 317534, tzinfo=datetime.timezone.utc)),
        ),
    ]
