# Generated by Django 4.1.7 on 2023-03-09 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 7, 18, 15, 153949, tzinfo=datetime.timezone.utc)),
        ),
    ]
