# Generated by Django 4.1.7 on 2023-03-09 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_author_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 12, 5, 16, 315583, tzinfo=datetime.timezone.utc)),
        ),
    ]
