# Generated by Django 4.1.7 on 2023-03-11 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 7, 14, 10, 616787, tzinfo=datetime.timezone.utc)),
        ),
    ]
