# Generated by Django 4.1.7 on 2023-03-11 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 7, 28, 15, 80122, tzinfo=datetime.timezone.utc)),
        ),
    ]
