# Generated by Django 4.1.7 on 2023-03-16 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 14, 56, 51, 767210, tzinfo=datetime.timezone.utc)),
        ),
    ]
